global using MDBEditor.Constants;
global using MDBEditor.Constants.Attributes;
global using MDBEditor.Constants.Enums;
global using MDBEditor.Constants.Models;
global using MDBEditor.Controls;
global using MDBEditor.Helpers;
global using MDBEditor.Pages.Modals;
global using MDBEditor.Shapes;
global using MDBEditor.Shapes.Common;
global using MDBEditor.Tools.Common;
global using MDBEditor.Tools.Concrete;
global using MDBEditor.Utils;
global using System;
global using System.Drawing;
global using System.Drawing.Printing;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Windows.Forms;
global using static MDBEditor.Constants.Global;
global using Rectangle = System.Drawing.Rectangle;
